#!/bin/bash

BASEDIR=$(dirname $0)
cd ${BASEDIR}
BASEDIR=$PWD

#-----------------------------------------------
# Run all setup scripts
#-----------------------------------------------
for SETUP_SCRIPT in $(ls | grep '^setup-' | egrep -v '~|#' )
do
    echo "${SETUP_SCRIPT}: Running"
    ./${SETUP_SCRIPT}
    echo "${SETUP_SCRIPT}: Done"
    echo
done
