#!/bin/bash

BASEDIR=$(dirname $0)
cd ${BASEDIR}
BASEDIR=$PWD


link_dot_files () {
    IGNORE_FILTER="${1}"
    INCLUDE_FILTER="${2}"
    #---------------------------------------------------
    # Link in all the dot files
    #---------------------------------------------------
    for DOT_FILE in $( ls -d dot-*  | egrep -v "$IGNORE_FILTER" | grep "$INCLUDE_FILTER" )
    do
	REAL_DOT_FILE=~/$(echo ${DOT_FILE} | sed -e 's/dot-/\./g' -e 's/-slash-/\//g' -e 's/://g' -e 's/\^.*//' )
	# echo $DOT_FILE
	DOT_FILE=$(echo ${DOT_FILE} |sed 's/://g')


	if [ -e ${REAL_DOT_FILE} ];then
	    FILE_TYPE=$(file ${REAL_DOT_FILE} | awk '{print $2" "$3}')
	    if [ "${FILE_TYPE}" == "symbolic link" ];then
		rm ${REAL_DOT_FILE}
		# continue
	    else
		# echo "Moving ${REAL_DOT_FILE} out of the way"
		mkdir -p $(dirname ${REAL_DOT_FILE})
		mv ${REAL_DOT_FILE} ${REAL_DOT_FILE}.backup
	    fi
	fi
	
	echo "Linking $REAL_DOT_FILE -> ${BASEDIR}/${DOT_FILE}"
	# For some reason base really didn't want to make this work.
	echo ln -s ${BASEDIR}/${DOT_FILE} ${REAL_DOT_FILE} |sh   
	echo
    done
}

# Base
link_dot_files "~$|#$|\^" ""

# OS 
link_dot_files "~$|#$" "\^$(uname)"

# hostname
link_dot_files "~$|#$" "\^$(hostname)"

