#!/bin/bash

BASEDIR=$(dirname $0)
cd ${BASEDIR}
BASEDIR=$PWD

#---------------------------------------------------
# Link in all the dot files
#---------------------------------------------------
for DOT_FILE in $( ls dot-*  | egrep -v '~$|#$' )
do
    REAL_DOT_FILE=~/$(echo ${DOT_FILE} | sed -e 's/dot-/\./g' -e 's/-slash-/\//g' )

    if [ -e ${REAL_DOT_FILE} ];then
	FILE_TYPE=$(file ${REAL_DOT_FILE} | awk '{print $2" "$3}')
	if [ "${FILE_TYPE}" == "symbolic link" ];then
	    echo "Skipping ${REAL_DOT_FILE} already a link"
	    continue
	else
	    echo "Moving ${REAL_DOT_FILE} out of the way"
	    mv ${REAL_DOT_FILE} ${REAL_DOT_FILE}.backup
	fi
    fi
    
    echo "Linking $REAL_DOT_FILE -> ${BASEDIR}/${DOT_FILE}"
    # For some reason base really didn't want to make this work.
    echo ln -s ${BASEDIR}/${DOT_FILE} ${REAL_DOT_FILE} | sh
    
    echo
done
